// 天気API実験の動きを担当するファイル。APIキーは使いません。
document.head.insertAdjacentHTML('beforeend', '<link rel="stylesheet" href="weather.css">');
const foundationLink = document.querySelector('a[href="lab.html"]'); if (foundationLink) foundationLink.textContent = 'Webの基礎';
const citySelect = document.querySelector('#city'); const fetchButton = document.querySelector('#fetch-weather'); const statusText = document.querySelector('#process-status'); const jsonOutput = document.querySelector('#json-output'); const steps = ['step-user', 'step-js', 'step-api', 'step-display'];
const fukuokaOption = document.createElement('option'); fukuokaOption.value = '33.5904,130.4017,福岡'; fukuokaOption.textContent = '福岡'; citySelect.appendChild(fukuokaOption);
const hakusanOption = document.createElement('option'); hakusanOption.value = '36.5144,136.5656,白山（石川）'; hakusanOption.textContent = '白山（石川）'; citySelect.appendChild(hakusanOption);
const weatherNames = {0:'快晴',1:'主に晴れ',2:'一部くもり',3:'くもり',45:'霧',51:'霧雨',61:'雨',63:'雨',65:'強い雨',71:'雪',80:'にわか雨',95:'雷雨'};
function showStep(stepIndex, message) { steps.forEach((id,index) => { const step = document.querySelector(`#${id}`); if (step) step.classList.toggle('step-active', index === stepIndex); }); statusText.textContent = message; }
async function getWeather() { const [latitude, longitude, name] = citySelect.value.split(','); fetchButton.disabled = true; showStep(0, `${name}を選択しました`); await new Promise(resolve => setTimeout(resolve, 350)); showStep(1, 'JavaScriptが天気APIへ問い合わせ中…'); const url = `https://api.open-meteo.com/v1/forecast?latitude=${latitude}&longitude=${longitude}&current=temperature_2m,weather_code&hourly=precipitation_probability&forecast_days=1&timezone=auto`; try { const response = await fetch(url); if (!response.ok) throw new Error(`HTTP ${response.status}`); const data = await response.json(); showStep(2, 'APIからJSONデータが返りました'); jsonOutput.textContent = JSON.stringify(data, null, 2); document.querySelector('#location-name').textContent = name; document.querySelector('#result-time').textContent = data.current?.time ?? '—'; document.querySelector('#temperature').textContent = data.current?.temperature_2m ?? '—'; document.querySelector('#weather-label').textContent = weatherNames[data.current?.weather_code] ?? `コード ${data.current?.weather_code ?? '—'}`; document.querySelector('#rain-chance').textContent = data.hourly?.precipitation_probability?.[0] ?? '—'; showStep(3, 'JSONから必要な値を取り出して表示しました'); } catch (error) { statusText.textContent = `取得に失敗しました：${error.message}`; jsonOutput.textContent = 'エラーのためJSONを表示できませんでした。時間をおいて再試行してください。'; } finally { fetchButton.disabled = false; } }
fetchButton.addEventListener('click', getWeather);
