// 天気API実験の動きを担当するファイル。APIキーは使いません。
document.head.insertAdjacentHTML('beforeend', '<link rel="stylesheet" href="weather.css">');
document.querySelector('.page-heading h1').insertAdjacentHTML('beforebegin', '<a href="index.html#roadmap" style="display:inline-block;border:1px solid #2a2e37;background:#151920;color:#f2f3ee;border-radius:999px;padding:8px 13px;text-decoration:none;font-size:12px;margin-bottom:14px">← ロードマップ</a>');
const citySelect = document.querySelector('#city'); const fetchButton = document.querySelector('#fetch-weather'); const statusText = document.querySelector('#process-status'); const jsonOutput = document.querySelector('#json-output'); const steps = ['step-user', 'step-js', 'step-api', 'step-display'];
const fukuokaOption = document.createElement('option'); fukuokaOption.value = '33.5904,130.4017,福岡'; fukuokaOption.textContent = '福岡'; citySelect.appendChild(fukuokaOption);
const weatherNames = {0:'快晴',1:'主に晴れ',2:'一部くもり',3:'くもり',45:'霧',51:'霧雨',61:'雨',63:'雨',65:'強い雨',71:'雪',80:'にわか雨',95:'雷雨'};
function showStep(stepIndex, message) { steps.forEach((id,index) => document.querySelector(`#${id}`).classList.toggle('step-active', index === stepIndex)); statusText.textContent = message; }
async function getWeather() { const [latitude, longitude, name] = citySelect.value.split(','); fetchButton.disabled = true; showStep(0, `${name}を選択しました`); await new Promise(resolve => setTimeout(resolve, 350)); showStep(1, 'JavaScriptが天気APIへ問い合わせ中…'); const url = `https://api.open-meteo.com/v1/forecast?latitude=${latitude}&longitude=${longitude}&current=temperature_2m,weather_code&hourly=precipitation_probability&forecast_days=1&timezone=auto`; try { const response = await fetch(url); if (!response.ok) throw new Error(`HTTP ${response.status}`); const data = await response.json(); showStep(2, 'APIからJSONデータが返りました'); jsonOutput.textContent = JSON.stringify(data, null, 2); document.querySelector('#location-name').textContent = name; document.querySelector('#result-time').textContent = data.current?.time ?? '—'; document.querySelector('#temperature').textContent = data.current?.temperature_2m ?? '—'; document.querySelector('#weather-label').textContent = weatherNames[data.current?.weather_code] ?? `コード ${data.current?.weather_code ?? '—'}`; document.querySelector('#rain-chance').textContent = data.hourly?.precipitation_probability?.[0] ?? '—'; showStep(3, 'JSONから必要な値を取り出して表示しました'); } catch (error) { statusText.textContent = `取得に失敗しました：${error.message}`; jsonOutput.textContent = 'エラーのためJSONを表示できませんでした。時間をおいて再試行してください。'; } finally { fetchButton.disabled = false; } }
fetchButton.addEventListener('click', getWeather);
